"""add shelf_name to shopper_tracking

Revision ID: 73181e0ce067
Revises: 281dadd1a9f1
Create Date: 2026-07-20 19:19:42.033584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73181e0ce067'
down_revision: Union[str, Sequence[str], None] = '281dadd1a9f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shopper_dwell_time_id'), table_name='shopper_dwell_time')
    op.drop_index(op.f('ix_shopper_dwell_time_track_id'), table_name='shopper_dwell_time')
    op.drop_table('shopper_dwell_time')
    op.drop_index(op.f('ix_shopper_tracking_id'), table_name='shopper_tracking')
    op.drop_table('shopper_tracking')
    op.alter_column('stores', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_stores_id'), 'stores', ['id'], unique=False)
    op.drop_column('stores', 'store_metadata')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('stores', sa.Column('store_metadata', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_stores_id'), table_name='stores')
    op.alter_column('stores', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('shopper_tracking',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('track_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('x1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('y1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('x2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('y2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('frame_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('shopper_tracking_pkey'))
    )
    op.create_index(op.f('ix_shopper_tracking_id'), 'shopper_tracking', ['id'], unique=False)
    op.create_table('shopper_dwell_time',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('track_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entry_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('exit_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('dwell_time_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('shopper_dwell_time_pkey'))
    )
    op.create_index(op.f('ix_shopper_dwell_time_track_id'), 'shopper_dwell_time', ['track_id'], unique=False)
    op.create_index(op.f('ix_shopper_dwell_time_id'), 'shopper_dwell_time', ['id'], unique=False)
    # ### end Alembic commands ###
