"""add product scores

Revision ID: 8cee4f1e7509
Revises: 73181e0ce067
Create Date: 2026-08-10 14:46:57.379656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cee4f1e7509'
down_revision: Union[str, Sequence[str], None] = '73181e0ce067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_scores',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('shelf_name', sa.String(), nullable=False),
        sa.Column('attention_duration', sa.Float(), nullable=True),
        sa.Column('interaction_frequency', sa.Float(), nullable=True),
        sa.Column('pickup_rate', sa.Float(), nullable=True),
        sa.Column('conversion_rate', sa.Float(), nullable=True),
        sa.Column('repeat_engagement', sa.Float(), nullable=True),
        sa.Column('attractiveness_score', sa.Float(), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=True
        ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(
        op.f('ix_product_scores_id'),
        'product_scores',
        ['id'],
        unique=False
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(
        op.f('ix_product_scores_id'),
        table_name='product_scores'
    )

    op.drop_table('product_scores')
