"""Add tracking and attention tables

Revision ID: 172658ef259e
Revises: dbd02336f27c
Create Date: 2026-07-19 08:00:22.635235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '172658ef259e'
down_revision: Union[str, None] = 'dbd02336f27c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopper_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=36), nullable=False),
    sa.Column('anonymous_id', sa.String(length=100), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_dwell_time_seconds', sa.Float(), nullable=False),
    sa.Column('path_data', sa.JSON(), nullable=False),
    sa.Column('zones_visited', sa.JSON(), nullable=False),
    sa.Column('consumer_segment', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracking_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('video_source', sa.String(length=500), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_frames_processed', sa.Integer(), nullable=False),
    sa.Column('total_persons_detected', sa.Integer(), nullable=False),
    sa.Column('unique_shoppers_count', sa.Integer(), nullable=False),
    sa.Column('avg_fps', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attention_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=36), nullable=False),
    sa.Column('shelf_id', sa.String(length=36), nullable=True),
    sa.Column('zone_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('gaze_x', sa.Float(), nullable=True),
    sa.Column('gaze_y', sa.Float(), nullable=True),
    sa.Column('head_yaw', sa.Float(), nullable=True),
    sa.Column('head_pitch', sa.Float(), nullable=True),
    sa.Column('head_roll', sa.Float(), nullable=True),
    sa.Column('attention_duration_seconds', sa.Float(), nullable=False),
    sa.Column('is_looking_at_shelf', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['shopper_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shelf_id'], ['shelves.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['store_zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dwell_time_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=36), nullable=False),
    sa.Column('shelf_id', sa.String(length=36), nullable=True),
    sa.Column('zone_id', sa.String(length=36), nullable=True),
    sa.Column('tracker_id', sa.Integer(), nullable=False),
    sa.Column('entry_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dwell_seconds', sa.Float(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['shopper_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shelf_id'], ['shelves.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['store_zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dwell_time_records')
    op.drop_table('attention_events')
    op.drop_table('tracking_sessions')
    op.drop_table('shopper_sessions')
    # ### end Alembic commands ###
